### ISSUE TITLE
SSL support [0.2.1] [Enhancement]

### ISSUE THREAD

**Issue by NoodleBB** [NodeBB/nodebb-plugin-emailer-local#9]
SSL/TLS support is strongly missing.

**Comment by fiag** [comment]
https://github.com/drlogout/nodebb-plugin-emailer-ssl-smtp

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-plugin-emailer-local/commit/d146219dbe29b960042d08ef879c0812ae431b75
